// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKfFE97uAbqz41UNYlmOveJm27mwl1pE4',
    appId: '1:575877406216:web:ca1bfab3835acb96fefbbd',
    messagingSenderId: '575877406216',
    projectId: 'tik-tok-bakq',
    authDomain: 'tik-tok-bakq.firebaseapp.com',
    storageBucket: 'tik-tok-bakq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTqkopMo43uiwZPJB3Mj2zEUwD89myQ9I',
    appId: '1:575877406216:android:326b33646cd7b0ccfefbbd',
    messagingSenderId: '575877406216',
    projectId: 'tik-tok-bakq',
    storageBucket: 'tik-tok-bakq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAz44RjbmgXUpkvRg3Pwv-0AIk_7e4fgs',
    appId: '1:575877406216:ios:541523b0248e0b05fefbbd',
    messagingSenderId: '575877406216',
    projectId: 'tik-tok-bakq',
    storageBucket: 'tik-tok-bakq.firebasestorage.app',
    iosBundleId: 'com.tiktokClone1',
  );

}